/* tslint:disable */
/* eslint-disable */
/**
 * Bee's Knees API
 * Bee's Knees backend API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse401 } from '../models';
import { MonoAccount } from '../models';
import { MonoaccountBody } from '../models';
/**
 * MonoaccountApi - axios parameter creator
 * @export
 */
export const MonoaccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all MonoAccounts associated with a BKUser.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getallmonoaccounts: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/monoaccount`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getmonoaccount: async (bKMonoAccountToken: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'bKMonoAccountToken' is not null or undefined
            if (bKMonoAccountToken === null || bKMonoAccountToken === undefined) {
                throw new RequiredError('bKMonoAccountToken','Required parameter bKMonoAccountToken was null or undefined when calling getmonoaccount.');
            }
            const localVarPath = `/monoaccount/{BKMonoAccountToken}`
                .replace(`{${"BKMonoAccountToken"}}`, encodeURIComponent(String(bKMonoAccountToken)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getmonoaccounttransactions: async (bKMonoAccountToken: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'bKMonoAccountToken' is not null or undefined
            if (bKMonoAccountToken === null || bKMonoAccountToken === undefined) {
                throw new RequiredError('bKMonoAccountToken','Required parameter bKMonoAccountToken was null or undefined when calling getmonoaccounttransactions.');
            }
            const localVarPath = `/monoaccount/{BKMonoAccountToken}/transactions`
                .replace(`{${"BKMonoAccountToken"}}`, encodeURIComponent(String(bKMonoAccountToken)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Link a MonoAccount associated with a BKUser.
         * @param {MonoaccountBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkmonoaccount: async (body: MonoaccountBody, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling linkmonoaccount.');
            }
            const localVarPath = `/monoaccount`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Unlink a MonoAccount associated with a BKUser.
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkmonoaccount: async (bKMonoAccountToken: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'bKMonoAccountToken' is not null or undefined
            if (bKMonoAccountToken === null || bKMonoAccountToken === undefined) {
                throw new RequiredError('bKMonoAccountToken','Required parameter bKMonoAccountToken was null or undefined when calling unlinkmonoaccount.');
            }
            const localVarPath = `/monoaccount/{BKMonoAccountToken}`
                .replace(`{${"BKMonoAccountToken"}}`, encodeURIComponent(String(bKMonoAccountToken)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MonoaccountApi - functional programming interface
 * @export
 */
export const MonoaccountApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get all MonoAccounts associated with a BKUser.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getallmonoaccounts(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MonoAccount>>> {
            const localVarAxiosArgs = await MonoaccountApiAxiosParamCreator(configuration).getallmonoaccounts(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getmonoaccount(bKMonoAccountToken: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MonoAccount>> {
            const localVarAxiosArgs = await MonoaccountApiAxiosParamCreator(configuration).getmonoaccount(bKMonoAccountToken, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getmonoaccounttransactions(bKMonoAccountToken: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MonoAccount>> {
            const localVarAxiosArgs = await MonoaccountApiAxiosParamCreator(configuration).getmonoaccounttransactions(bKMonoAccountToken, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Link a MonoAccount associated with a BKUser.
         * @param {MonoaccountBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async linkmonoaccount(body: MonoaccountBody, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MonoAccount>> {
            const localVarAxiosArgs = await MonoaccountApiAxiosParamCreator(configuration).linkmonoaccount(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Unlink a MonoAccount associated with a BKUser.
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unlinkmonoaccount(bKMonoAccountToken: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await MonoaccountApiAxiosParamCreator(configuration).unlinkmonoaccount(bKMonoAccountToken, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MonoaccountApi - factory interface
 * @export
 */
export const MonoaccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get all MonoAccounts associated with a BKUser.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getallmonoaccounts(options?: any): AxiosPromise<Array<MonoAccount>> {
            return MonoaccountApiFp(configuration).getallmonoaccounts(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getmonoaccount(bKMonoAccountToken: string, options?: any): AxiosPromise<MonoAccount> {
            return MonoaccountApiFp(configuration).getmonoaccount(bKMonoAccountToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getmonoaccounttransactions(bKMonoAccountToken: string, options?: any): AxiosPromise<MonoAccount> {
            return MonoaccountApiFp(configuration).getmonoaccounttransactions(bKMonoAccountToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Link a MonoAccount associated with a BKUser.
         * @param {MonoaccountBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkmonoaccount(body: MonoaccountBody, options?: any): AxiosPromise<MonoAccount> {
            return MonoaccountApiFp(configuration).linkmonoaccount(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Unlink a MonoAccount associated with a BKUser.
         * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkmonoaccount(bKMonoAccountToken: string, options?: any): AxiosPromise<void> {
            return MonoaccountApiFp(configuration).unlinkmonoaccount(bKMonoAccountToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MonoaccountApi - object-oriented interface
 * @export
 * @class MonoaccountApi
 * @extends {BaseAPI}
 */
export class MonoaccountApi extends BaseAPI {
    /**
     * Get all MonoAccounts associated with a BKUser.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MonoaccountApi
     */
    public getallmonoaccounts(options?: any) {
        return MonoaccountApiFp(this.configuration).getallmonoaccounts(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MonoaccountApi
     */
    public getmonoaccount(bKMonoAccountToken: string, options?: any) {
        return MonoaccountApiFp(this.configuration).getmonoaccount(bKMonoAccountToken, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MonoaccountApi
     */
    public getmonoaccounttransactions(bKMonoAccountToken: string, options?: any) {
        return MonoaccountApiFp(this.configuration).getmonoaccounttransactions(bKMonoAccountToken, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Link a MonoAccount associated with a BKUser.
     * @param {MonoaccountBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MonoaccountApi
     */
    public linkmonoaccount(body: MonoaccountBody, options?: any) {
        return MonoaccountApiFp(this.configuration).linkmonoaccount(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Unlink a MonoAccount associated with a BKUser.
     * @param {string} bKMonoAccountToken BKMonoAccount (lookup token, not MonoId) id of account to be retrieved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MonoaccountApi
     */
    public unlinkmonoaccount(bKMonoAccountToken: string, options?: any) {
        return MonoaccountApiFp(this.configuration).unlinkmonoaccount(bKMonoAccountToken, options).then((request) => request(this.axios, this.basePath));
    }
}
