/* tslint:disable */
/* eslint-disable */
/**
 * Bee's Knees API
 * Bee's Knees backend API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MonoAccount
 */
export interface MonoAccount {
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof MonoAccount
     */
    linkedOnDate?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    currency?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    accountType?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    accountNumber?: any;
    /**
     * 
     * @type {number}
     * @memberof MonoAccount
     */
    balance?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    bvn?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    institutionName?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    institutionBankCode?: any;
    /**
     * 
     * @type {string}
     * @memberof MonoAccount
     */
    institutionType?: any;
}
