/* tslint:disable */
/* eslint-disable */
/**
 * Bee's Knees API
 * Bee's Knees backend API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TokenInfo
 */
export interface TokenInfo {
    /**
     * 
     * @type {number}
     * @memberof TokenInfo
     */
    id?: any;
    /**
     * Username
     * @type {string}
     * @memberof TokenInfo
     */
    username?: any;
    /**
     * access token status
     * @type {string}
     * @memberof TokenInfo
     */
    accessToken?: any;
}
