/* tslint:disable */
/* eslint-disable */
/**
 * Bee's Knees API
 * Bee's Knees backend API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {UserInfoUser}
     * @memberof UserInfo
     */
    user?: any;
    /**
     * Access Token
     * @type {string}
     * @memberof UserInfo
     */
    accessToken?: any;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    expiresIn?: any;
    /**
     * Refresh Token
     * @type {string}
     * @memberof UserInfo
     */
    refreshToken?: any;
}
