/* tslint:disable */
/* eslint-disable */
/**
 * Bee's Knees API
 * Bee's Knees backend API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * Username
     * @type {string}
     * @memberof User
     */
    username?: any;
    /**
     * password
     * @type {string}
     * @memberof User
     */
    password?: any;
}
